import { ModelType } from "@/schemas";
import { IOutputStrategy } from "./output-strategy";

export class MySQLStrategy extends IOutputStrategy {
  generateSchema(model: ModelType) {
    let sqlOutput = "";

    sqlOutput += `-- ${model.name} schema generated by khld.dev\n\n`;
    for (const nty of model.entities) {
      let uniqueAttributes = [];
      sqlOutput += `CREATE TABLE ${this.toSnakeCase(nty.name)} (\n`;
      for (const attr of nty.attributes) {
        sqlOutput += `  ${this.toSnakeCase(attr.name)} ${String(
          this.columnType(attr.type)
        ).toUpperCase()}`;
        if (attr.type === "serial") {
          sqlOutput += " AUTO_INCREMENT";
        }
        if (attr.primaryKey) {
          sqlOutput += " PRIMARY KEY";
        }
        if (!attr.nullable && !attr.primaryKey) {
          sqlOutput += " NOT NULL";
        }
        if (attr.default) {
          sqlOutput += ` DEFAULT ${attr.default}`;
        }
        sqlOutput +=
          attr !== nty.attributes[nty.attributes.length - 1] ? `,\n` : `\n`;
        attr.unique && uniqueAttributes.push(attr.name);
      }
      for (const unique of uniqueAttributes) {
        sqlOutput += `  UNIQUE (${this.toSnakeCase(unique)})`;
        sqlOutput +=
          unique !== uniqueAttributes[uniqueAttributes.length - 1]
            ? `,\n`
            : `\n`;
      }
      sqlOutput += `);\n\n`;
    }
    return sqlOutput;
  }

  private columnType = (type: string): string => {
    switch (type) {
      case "serial":
        return "INT";
      case "string":
        return "VARCHAR(255)";
      case "number":
        return "INT";
      case "json":
        return "JSON";
      case "date":
        return "DATE";
      case "boolean":
        return "BOOLEAN";
      case "timestamp":
        return "TIMESTAMP";
      case "money":
        return "DECIMAL(10, 2)";
      default:
        throw new Error(`Unsupported field type: ${type}`);
    }
  };
}
