import { ModelType } from "@/schemas";
import { AbstractOutputStrategy } from "./output-strategy";

export class PostgresStrategy extends AbstractOutputStrategy {
  generateSchema(model: ModelType) {
    let sqlOutput = "";

    sqlOutput += `-- ${model.name} schema generated by khld.dev\n\n`;
    for (const nty of model.entities) {
      let uniqueAttributes = [];
      sqlOutput += `CREATE TABLE ${this.toSnakeCase(nty.name)} (\n`;
      for (const attr of nty.attributes) {
        sqlOutput += `  ${this.toSnakeCase(attr.name)} ${String(
          this.columnType(attr.type)
        ).toUpperCase()}`;
        sqlOutput += attr.primaryKey ? ` PRIMARY KEY` : "";
        sqlOutput += attr.default ? ` DEFAULT ${attr.default}` : "";
        // not null
        sqlOutput += attr.nullable && !attr.primaryKey ? "" : " NOT NULL";
        sqlOutput +=
          attr !== nty.attributes[nty.attributes.length - 1]
            ? `,\n`
            : attr.unique
            ? `,\n`
            : `\n`;
        attr.unique && uniqueAttributes.push(attr.name);
      }
      for (const unique of uniqueAttributes) {
        sqlOutput += `  UNIQUE (${this.toSnakeCase(unique)})`;
        sqlOutput +=
          unique !== uniqueAttributes[uniqueAttributes.length - 1]
            ? `,\n`
            : `\n`;
      }
      sqlOutput += `);\n\n`;
    }
    return sqlOutput;
  }

  private columnType = (type: string): string => {
    switch (type) {
      case "serial":
        return "SERIAL";
      case "string":
        return "text";
      case "number":
        return "integer";
      case "json":
        return "jsonb";
      case "date":
        return "date";
      case "boolean":
        return "boolean";
      case "timestamp":
        return "timestamp";
      case "money":
        return "money";
      default:
        throw new Error(`Unsupported field type: ${type}`);
    }
  };
}
