import { ModelType } from "@/schemas/tables-schema";
import { AbstractOutputStrategy } from "./output-strategy";

export default class PrismaStrategy extends AbstractOutputStrategy {
  generateSchema(model: ModelType) {
    let prismaOutput = "";

    prismaOutput += `// ${model.name} schema generated by khld.dev\n\n`;
    // for (const nty of model.entities) {
    //   prismaOutput += `model ${this.toPascalCase(nty.name)} {\n`;
    //   for (const attr of nty.attributes) {
    //     prismaOutput += `  ${this.toSnakeCase(attr.name)} ${String(
    //       this.columnType(attr.type)
    //     ).toLowerCase()}`;
    //     if (attr.primaryKey) {
    //       prismaOutput += " @id";
    //     }
    //     if (attr.default) {
    //       prismaOutput += ` @default(${attr.default})`;
    //     }
    //     if (attr.unique) {
    //       prismaOutput += " @unique";
    //     }
    //     prismaOutput += `\n`;
    //   }
    //   prismaOutput += `}\n\n`;
    // }
    return prismaOutput;
  }
}
