import { ThemeProvider } from "@/components/ui/theme-provider";

import { ReactFlowProvider } from "@/components/ReactFlowProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full" lang="en" suppressHydrationWarning>
      <head />
      <body className="w-full h-full ">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReactFlowProvider>{children}</ReactFlowProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
